### ISSUE TITLE
extension:install composer packages

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-console#14]
If a package name (vendor/package) is passed to the extension:install command, install it using Composer

**Comment by yiendos** [comment]
@stevenrombauts the above commit was started at the Timble Workshop. On the train you said there might be other relevant tickets relating to composer?

**Comment by stevenrombauts** [comment]
@yiendos I was referring to tickets #21 and #28. But this ticket is still unrelated to those right now: here we just want to be able to install components by package name instead of local directory. 

For example: `joomla extension:install joomlatools/joomla-todo` should recognise the name as a Composer package (format foo/bar) and instead of calling the bootstrapper and the installer logic, it should do a `composer require <package name>`.

**Comment by yiendos** [comment]
## Note regex used in branch 

Is tested against the following: 
https://regex101.com/r/fHlWZZ/1

**Comment by stevenrombauts** [comment]
@yiendos Does this require any more work?

**Comment by yiendos** [comment]
hmmm @stevenrombauts I honestly can't remember the state of this ticket. I can jump back in and refresh myself with the code

**Comment by stevenrombauts** [comment]
Thanks @yiendos, nothing urgent, it looks like this code is basically finished so no reason not to include it in the upcoming 1.5 release then - unless it needs a lot more work.

**Comment by stevenrombauts** [comment]
Working like a charm, @yiendos. Thanks!
