### ISSUE TITLE
Add site:list command

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-console#17]
List all available sites.

**Comment by stevenrombauts** [comment]
@rodolfovillaruz An additional improvement to this ticket would be to add an `--format` option. We could have two formats: text and json. 

Since we are now re-using the same code from the joomlatools-vagrant dashboard file, we could replace that code with a call to `site:list` to get the json data and then parse it out. If we add new versions or fixes we only have to update the code once, in joomlatools-console.

**Comment by johanjanssens** [comment]
@stevenrombauts Can you please review this?
