### ISSUE TITLE
Add superuser params

### ISSUE THREAD

**Issue by xcidar** [joomlatools/joomlatools-console#45]
Add pls superuser login:password parameters to site:create and/or site:install to create a custom superuser for the first install. Admin/admin is kinda unsecure.

**Comment by johanjanssens** [comment]
Hello Jan, the issue tracker is only for development, nor for questions or suggestions. For questions or discussion of our open tools you can use our [gitter chat](joomlatools/dev on Gitter) or [forums](https://groups.google.com/forum/#!forum/joomlatools-dev). 

For more info on how to contribute please read our contributions guidelines: https://www.joomlatools.com/developer/contribute/

Thanks!

**Comment by tomsommer** [comment]
This is clearly a problem. How can you deploy something with admin/admin credentials in 2020?

Please reconsider this request

**Comment by stevenrombauts** [comment]
@tomsommer We use this tool with the aim of setting up a local development site quickly, mostly for testing extension installs. That's why we use a default admin/admin combination.  If and when you would deploy to a live environment, we assume you will change the username and password, along with anything else that needs configuring.

Nonetheless it's an interesting idea to provide this option. We're always open to new contributions, please see our contributions guidelines here: https://www.joomlatools.com/developer/contribute/ If you have any questions on where to start, just ask! I'm happy to help.
